name: pub_insights
description: A tool for downloading pub packages and running analysis on them. 
version: 1.0.0
# repository: https://github.com/loic-sharma/pub_insights

environment:
  sdk: ^3.0.0-430.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  archive: ^3.3.7
  async: ^2.11.0
  console_bars: ^1.1.0
  http: ^0.13.5
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
